name: Add script
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
     
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
 
      - name: Print Greeting
        run: echo "${{ vars.Add }} Welcome to GitHub Actions."
 
      - name: Print Working Directory
        run: |
          pwd
          ls -l
 
      - name: Adding Script to my workflow
        run: |
          bash /home/runner/work/GH_ACT_2/GH_ACT_2/script.sh
