name: Add script
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
     
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
 
      - name: Print Greeting
        run: echo "${{ vars.USER_NAME }} Welcome to GitHub Actions."
 
      - name: Print Working Directory
        run: |
          pwd
          ls -l
 
      # - name: Run Custom Script
      #   run: |
      #     bash /home/runner/work/gitaction_poc1_2/
